name: "Linting & Testing"

on: [push]

jobs:
  static-checks:
    name: 'Static Checks'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Scony/godot-gdscript-toolkit@master
    - run: gdlint src/
    
  gut-unit-tests:
    name: 'GUT Unit Tests'
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Godot import
        run: godot --headless --import --path "$PWD"
      - name: GUT test
        run: godot --headless -d -s --path "$PWD" addons/gut/gut_cmdln.gd -gdir=res://test/unit_tests -gsuffix=".test.gd" -gprefix="" -gexit
